version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10.0
    working_directory: ~/amphtml-validator-rules
    steps:
      - checkout
      - restore_cache:
          name: Restore node_modules cache
          keys:
            - v1-node-{{ arch }}-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v1-node-{{ arch }}-{{ .Branch }}-
            - v1-node-{{ arch }}-
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Generate Rules
          command: npm run generate
      - run:
          name: Build Distributable
          command: npm run build
      - run:
          name: Test
          command: npm run test
      - save_cache:
          name: Save node_modules cache
          key: v1-node-{{ arch }}-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
